### ISSUE TITLE
Unable to create Browser object

### ISSUE THREAD

**Issue by mnadig** [ryanpetrello/python-zombie#12]
> > > from zombie import Browser
> > > b = Browser()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/zombie/browser.py", line 32, in **init**
> > >     server = ZombieProxyServer()
> > >   File "/Library/Python/2.7/site-packages/zombie/proxy/server.py", line 58, in ZombieProxyServer
> > >     instances[cls] = cls(_args, *_kwargs)
> > >   File "/Library/Python/2.7/site-packages/zombie/proxy/server.py", line 110, in **init**
> > >     "The proxy server has not replied within 3 seconds."
> > > RuntimeError: The proxy server has not replied within 3 seconds.

**Comment by mario-grgic** [comment]
I have zombie node.js module installed globally, and this still does not work for me?

**Comment by dulsao** [comment]
I get the same error, running on win32 python 2.7.8. error appears both on installing with npm, with setup.py install, and pip install zombie

**Comment by dulsao** [comment]
Here is the code :
`from zombie import Browser`
`b = Browser()`

Here is the traceback :

`Traceback (most recent call last):
  File "C:\Users\user\Desktop\1.py", line 2, in <module>
    b = Browser()
  File "C:\Python27\lib\site-packages\zombie\browser.py", line 32, in __init__
    server = ZombieProxyServer()
  File "C:\Python27\lib\site-packages\zombie\proxy\server.py", line 58, in ZombieProxyServer
    instances[cls] = cls(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zombie\proxy\server.py", line 98, in __init__
    stderr=subprocess.STDOUT
  File "C:\Python27\lib\subprocess.py", line 710, in __init__''
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified`

Hope that hepls.
