### ISSUE TITLE
Form rendering

### ISSUE THREAD

**Issue by oscarmlage** [ryanpetrello/python-zombie#13]
First of all let me say that I don't know if this is the proper place to write this, but it's the one I felt "nearest" to my problem, sorry if it doesn't, feel free to close this issue if it's a wrong place.

I'm working testing a project using node v0.8.23 (http://nodejs.org/dist/v0.8.23/),  npm 1.4.4, zombie 1.4.1
and python-zombie 0.1.0a5. The template I'm trying to render while testing has a code like:

    <form action="custom/url/delete" method="POST">
        <button type="submit" name="submit" >Delete</button>
    </form>

The test I'm trying to run is:

    from zombie import Browser
    ...
    def test_remove_category(self):
        browser = self.browser
        ...
        # Go to the edit link
        browser.clickLink('a[href$="/edit"]')
        import pdb; pdb.set_trace()
        browser.pressButton('form[action$=delete] button[type=submit]')
        ...

The problem is the *pressButton* line (ignore the pdb for a moment), it's trying to press the button inside the form but the test is failing raising an error like:

    NodeError: Error: No BUTTON 'form[action$=delete] button[type=submit]'

Trying to debug the problem - now is where pdb gets the focus - I got that the form was not nicely rendered:

    (Pdb) print(browser.html())
    ....
    <form method="POST" action="custom/url/delete"></form>
        <button type="submit" name="submit">Delete</button>

It's like the button is outside the form, I was added some more elements like <ul><li></li></li> and some others just for debug purposes and they're been rendered ok, but seems that all the forms are opened and closed in same line and below all the inputs/buttons/whatever that must be **inside** the form.

Thinking in the project it's not an easy task to change the versions, had a try with latest version but there where some other errors that didn't allow me to see if this one is already fixed, anyone may help me a bit or give me any hint to know what's happening? Thanks in advance.

**Comment by oscarmlage** [comment]
Forget about it, it was due the form was not correctly placed in the template, it was between a table and it's not allowed to be a child element of a table, tr or tbody (http://stackoverflow.com/questions/5967564/form-inside-a-table).

**Comment by ryanpetrello** [comment]
:)
