### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by Nux-xader** [ryanpetrello/python-zombie#15]
i was declarate browser var with class Browser, my code like that

from zombie import Browser

browser = Browser()

browser.visit("http://satria-rahmat.herokuapp.com/caritahu")
browser.pressButton("/html/body/div[2]/form/button")
print(dir(browser))

but i get this error
AttributeError: module 'socket' has no attribute 'AF_UNIX'

**Comment by ryanpetrello** [comment]
Hey @Nux-xader,

This project is no longer maintained.  If you're wanting to do headless testing in Python, I recommend checking out https://playwright.dev/

**Comment by Nux-xader** [comment]
@ryanpetrello do you have any suggestions for making an automation system that can watch live streaming with very small resource usage
